services:
  pc-control:
    build: .
    container_name: pc-control
    restart: always
    network_mode: host
    environment:
      - PORT=3003
    volumes:
      - /DATA/AppData/pc-controller/data:/app/data